#!/bin/bash

traces=("case" "exchange" "homes" "ikki")
ssds=("base" "fast")

rm -r output

for t in ${traces[@]}; do
for s in ${ssds[@]}; do
    mkdir -p output/$t/$s
    ./simexe-r config/$t.cfg simplessd/config/$s.cfg output/$t/$s 1> output/$t/$s/stdout 2> output/$t/$s/stderr &
done
done

