# Biochem. Lab. Data Analysis

## Environment Setup

```{r}
library(tidyverse)  # import tidyverse
```

```{r}
getwd() # check current working directory
```

```{r}
setwd("/Users/peiyuliu/Desktop/PKU-Undergraduate-Course-Public/生物化学实验(Biochemistry Lab)/Week 9")
getwd() # set current working directory
```

## Pre-process

```{r}
# load data from disk
enzymeActivityData <- read.csv("./result-Total.csv")
head(enzymeActivityData)
# view(enzymeActivityData)
```

```{r}
# drop useless data
enzymeActivityData = enzymeActivityData[, 1:7] 
head(enzymeActivityData)
```

```{r}
# group by different factors (pH or different homogenizers)
method = enzymeActivityData[enzymeActivityData$Method_Group == 0,]
pH = enzymeActivityData[enzymeActivityData$Method_Group == 1,]
```

```{r}
# check results
head(method)
head(pH)
```

```{r}
# extract individual methods (useless here)
# method_elec = method[method$Method == "Electric homogenizer", ]
# method_glass = method[method$Method == "Glass homogenizer", ]
# method_bead = method[method$Method == "Bead mill homogenizer", ]
# pH6.0 = pH[pH$Method == "pH6.0", ]
# pH6.5 = pH[pH$Method == "pH6.5", ]
# pH7.0 = pH[pH$Method == "pH7.0", ]
# pH7.5 = pH[pH$Method == "pH7.5", ]
```

## Visualization

```{r}
boxplot_pH_avg <- ggplot(pH, aes(x = Method, y = Enzyme_Activity_avg, color = Method))
boxplot_pH <- boxplot_pH_avg + geom_boxplot() + geom_jitter(width = 0.2, alpha = 0.8) + labs(x = "pH", y = "Enzyme Activity")
ggsave("boxplot_pH.pdf", plot = boxplot_pH, device = "pdf")
boxplot_pH
```

```{r}
boxplot_pH_avg_norm <- ggplot(pH, aes(x = Method, y = Enzyme_Activity_avg_norm, color = Method))
boxplot_pH_norm <- boxplot_pH_avg_norm + geom_boxplot() + geom_jitter(width = 0.2, alpha = 0.8) + labs(x = "pH", y = "Enzyme Activity")
ggsave("boxplot_pH_norm.pdf", plot = boxplot_pH_norm, device = "pdf")
boxplot_pH_norm
```

```{r}
boxplot_method_avg <- ggplot(method, aes(x = Method, y = Enzyme_Activity_avg, color = Method))
boxplot_method <- boxplot_method_avg + geom_boxplot() + geom_jitter(width = 0.2, alpha = 0.8) + labs(x = "Method", y = "Enzyme Activity")
ggsave("boxplot_method.pdf", plot = boxplot_method, device = "pdf")
boxplot_method
```

```{r}
boxplot_method_avg_norm <- ggplot(method, aes(x = Method, y = Enzyme_Activity_avg_norm, color = Method))
boxplot_method_norm <- boxplot_method_avg_norm + geom_boxplot() + geom_jitter(width = 0.2, alpha = 0.8) + labs(x = "Method", y = "Enzyme Activity")
ggsave("boxplot_method_norm.pdf", plot = boxplot_method_norm, device = "pdf")
boxplot_method_norm
```

## Analysis

```{r}
anova1 <- aov(Enzyme_Activity_avg_norm~Method, method)
summary(anova1)
```

```{r}
anova2 <- aov(Enzyme_Activity_avg_norm~Method, pH)
summary(anova2)
```
