---
title: "R Notebook"
output: html_notebook
---

```{r}
getwd()
```

```{r}
setwd("/Users/peiyuliu/Desktop/PKU-Undergraduate-Course-Public/生物化学实验(Biochemistry Lab)/Week 9")
getwd()
```

```{r}
enzymeActivityData <- read.csv("./result-Total.csv")
head(enzymeActivityData)
```

```{r}
enzymeActivityData = enzymeActivityData[, 1:7]
head(enzymeActivityData)
```

```{r}
method = enzymeActivityData[enzymeActivityData$Method_Group == 0,]
pH = enzymeActivityData[enzymeActivityData$Method_Group == 1,]
```

```{r}
head(method)
head(pH)
```

```{r}
method_elec = method[method$Method == "Electric homogenizer", ]
head(method_elec)
```

```{r}
method_glass = method[method$Method == "Glass homogenizer",]
method_bead = method[method$Method == "Bead mill homogenizer",]
pH6.0 = pH[pH$Method == "pH6.0",]
pH6.5 = pH[pH$Method == "pH6.5",]
pH7.0 = pH[pH$Method == "pH7.0",]
pH7.5 = pH[pH$Method == "pH7.5",]
```

## Visualization

```{r}
library(ggplot2)
```

```{r}
fig_pH_avg <- ggplot(pH, aes(x = Method, y = Enzyme_Activity_avg, color = Method))
fig_pH_avg + geom_boxplot() + geom_point() + labs(x = "pH", y = "Enzyme Activity")
```

```{r}
fig_pH_avg_norm <- ggplot(pH, aes(x = Method, y = Enzyme_Activity_avg_norm, color = Method))
fig_pH_avg_norm + geom_boxplot() + geom_point() + labs(x = "pH", y = "Enzyme Activity")
```

```{r}
fig_method_avg <- ggplot(method, aes(x = Method, y = Enzyme_Activity_avg, color = Method))
fig_method_avg + geom_boxplot() + geom_point() + labs(x = "Method", y = "Enzyme Activity")
```

```{r}
fig_method_avg_norm <- ggplot(method, aes(x = Method, y = Enzyme_Activity_avg_norm, color = Method))
fig_method_avg_norm + geom_boxplot() + geom_point() + labs(x = "Method", y = "Enzyme Activity")

```
