---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

## Step0. 安装所需包并载入

### 请补全代码(计1分)

```{r}
# install.packages("BiocManager")
# BiocManager::install("DESeq2")
install.packages("tidyverse")
library(DESeq2, tidyverse)
```

## Step1. 导入数据

### 从TCGA 网站下载表达量数据并解压缩

```{r}
path <- "/Users/peiyuliu/Desktop/PKU-Undergraduate-Course-Public/生物信息学实验(Bioinformatics Lab.)/Week3/data/TCGA-LIHC.star_counts.tsv"
```

### 将表达量数据读入R，数据框命名为raw （计1分）

```{r}
raw <- read.csv(path, sep = "\t")
head(raw)
```

### 数据转换

```{r}
rownames(raw) <- raw[, 1]
raw <- raw[, -1] # 给这句代码撰写注释，计1分：去除raw中的第一列
raw <- as.matrix(raw)
cts <- floor(2**raw-1)
```

### 生成样本类型数据框

```{r}
condition <- ifelse(substr(colnames(raw),14,14)=='0','tumor','normal') 
# 给这句代码撰写注释，计1分：判断raw每一列的列名的第14个字符是否为‘0’，如果是，则将condition中的对应位置修改为'tumor'，如果不是，则修改为'normal'
coldata <- as.data.frame(condition,colnames(raw))
coldata$condition <- factor(coldata$condition)
head(coldata)
```

## Step2. 构建*DESeqDataSet*（计1分）

```{r}
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ condition)
dds
```

## Step3. 预过滤

### 筛选总count\>=10的基因（计1分）

```{r}
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep, ]
dds
```

## Step4. 差异表达分析

### 对TCGA数据进行差异表达分析，得到结果表格（计1分）

```{r}
dds <- DESeq(dds)
res <- results(dds, contrast = c("condition", "tumor", "normal"), alpha = 0.05)
res
```

```{r}
mcols(res)$description
```

## Step5. 结果整理

### 练习：使用summary函数整理结果（计1分）

```{r}
summary(res)
```

```{r}
resOrdered <- res[order(res$pvalue),]
```

## Step6. 可视化

### 练习：选取某个基因作图展示表达量变化（计1分）

```{r}
plotCounts(dds, gene = which.min(res$padj), intgroup = "condition")
```

### 火山图

```{r}
# BiocManager::install("EnhancedVolcano")
library(EnhancedVolcano)
```

```{r, fig.width=20, fig.height=20}
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'log2FoldChange',
    y = 'pvalue',)
```
